services:
  api:
    build: .
    container_name: assignment3-gan
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./outputs:/app/outputs
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
